name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
      SSH_USER: ${{ vars.SSH_USER }}
      REMOTE_HOST: ${{ vars.REMOTE_HOST }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE_NAME }} .

      - name: Save Docker image
        run: |
          docker save ${{ env.DOCKER_IMAGE_NAME }} -o ${{ env.DOCKER_IMAGE_NAME }}.tar
          chmod 444 ${{ env.DOCKER_IMAGE_NAME }}.tar
      - name: Copy Docker image to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ${{ env.DOCKER_IMAGE_NAME }}.tar
          target: /home/${{ env.SSH_USER }}

      - name: SSH into remote server and load Docker container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker ps -a --filter "ancestor=${{ env.DOCKER_IMAGE_NAME }}" -q | xargs -r docker stop >/dev/null 2>&1
            docker ps -a --filter "ancestor=${{ env.DOCKER_IMAGE_NAME }}" -q | xargs -r docker rm >/dev/null 2>&1
            docker load -i /home/${{ env.SSH_USER }}/${{ env.DOCKER_IMAGE_NAME }}.tar
            docker run -d \
              -e "SecretKey=${{ secrets.SECRET_KEY }}" \
              -e "ConnectionStrings__DefaultConnection=${{ secrets.CONNECTION_STRING }}" \
              -e "Redis=${{ secrets.REDIS }}" \
              -e "Minio:EndPoint=${{ vars.MINIO_ENDPOINT }}" \
              -e "Minio:AccessKey=${{ secrets.MINIO_ACCESSKEY }}" \
              -e "Minio:SecretKey=${{ secrets.MINIO_SECRETKEY }}" \
              -e "Minio:BucketName=${{ vars.MINIO_BUCKETNAME }}" \
              -e "Minio:UseSSL=${{ vars.MINIO_USESSL }}" \
              -p 1111:8080 \
              -p 1112:8081 \
              ${{ env.DOCKER_IMAGE_NAME }}
            rm /home/${{ env.SSH_USER }}/${{ env.DOCKER_IMAGE_NAME }}.tar
